### ISSUE TITLE
Camdram login produces internal error page 

### ISSUE THREAD

**Issue by luciarc** [CHTJonas/roombooking#214]
attempted to log in a few times through camdram - have clicked 'allow' when redirected to camdram itself but keep getting an error 500 message from the internal server

**Comment by CHTJonas** [comment]
Thanks for bringing this to my attention! Could I just quickly check - is the error message you're seeing on Camdram or on Room Booking?

**Comment by luciarc** [comment]
It’s on the camdram page itself!

**Comment by CHTJonas** [comment]
Have tagged this as 'invalid' from the point of view of Room Booking since it was actually a bug in Camdram (camdram/camdram#622) but regardless it's now fixed and everything should be working as expected! Thanks again 😃
