### ISSUE TITLE
Can't make bookings for certain shows I have admin control over?

### ISSUE THREAD

**Issue by luciarc** [CHTJonas/roombooking#224]
I can currently only make bookings for rehearsals/meetings/auditions of panto or meetings of cuadc - I am also the only show admin for the three freshers plays this year (Nell Gwynn, Bloody Chamber, and Beautiful Thing), and am trying to book auditions using the shows so I don't use up all of CUADC's booking time, but there's no option for me to book through them on the bookings page?

**Comment by CHTJonas** [comment]
Looks like none of those shows have been imported into the system. Unfortunately whilst I can see they’re not yet imported, it’s a little outside my remit as a developer to enable them; if you speak to someone in Management they should be able to sort things for you!
